'use client';

import { useEffect, useMemo, useState } from 'react';

const SUPABASE_URL = 'https://oockmhrqgildjcuiwkfs.supabase.co';
const SUPABASE_KEY = 'sb_publishable_uH7pSxDr5JGwS7Mw2lxeGw_KkYoskfc';
const TABLE_URL = `${SUPABASE_URL}/rest/v1/ghg_records`;
const SESSION_KEY = 'aps-esg-session';
const factors = { Electricity:{scope:2,unit:'kWh',factor:.4999}, LPG:{scope:1,unit:'kg',factor:3.001}, Diesel:{scope:1,unit:'L',factor:2.676}, Gasoline:{scope:1,unit:'L',factor:2.271}, Refrigerant:{scope:1,unit:'kg',factor:1430}, Water:{scope:3,unit:'m³',factor:.344}, Waste:{scope:3,unit:'kg',factor:.587}, 'Business Travel':{scope:3,unit:'km',factor:.18}, 'Employee Commute':{scope:3,unit:'km',factor:.12}, Other:{scope:3,unit:'unit',factor:1} };
const factories=['HEAD FACTORY','SOUTH FACTORY','NORTH FACTORY','EAST FACTORY'];
const companies=['APS','TFW','KTG','UIM','OTHER'];
const navItems=[['dashboard','▦','Dashboard'],['entry','+','Activity Data'],['records','≣','GHG Records'],['factors','◎','Emission Factors'],['reports','▤','Reports']];
const fmt=(v,d=3)=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});

function ApsLogo({compact=false}){return <div className={`apsLogo ${compact?'compact':''}`} aria-label="A.P.S logo"><svg viewBox="0 0 120 120" role="img"><circle cx="60" cy="52" r="42"/><circle cx="60" cy="52" r="33"/><path d="M37 89 C50 82 70 82 83 89"/><text x="60" y="102" textAnchor="middle">A.P.S</text></svg></div>}

export default function Home(){
 const today=new Date().toISOString().slice(0,10), monthNow=today.slice(0,7);
 const [session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[auth,setAuth]=useState({email:'',password:''}),[authMessage,setAuthMessage]=useState('');
 const [page,setPage]=useState('dashboard'),[menuOpen,setMenuOpen]=useState(false),[records,setRecords]=useState([]),[loading,setLoading]=useState(false),[editId,setEditId]=useState(null);
 const [filter,setFilter]=useState({search:'',month:'',factory:'',scope:''});
 const [form,setForm]=useState({record_date:today,record_month:monthNow,factory:factories[0],company:companies[0],scope:2,source:'Electricity',activity_data:'',unit:'kWh',emission_factor:.4999,remark:''});
 useEffect(()=>{const s=localStorage.getItem(SESSION_KEY)||localStorage.getItem('taps-esg-session');if(s)try{setSession(JSON.parse(s))}catch{}},[]);
 useEffect(()=>{if(session?.access_token)loadRecords()},[session]);
 const headers=(extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...extra});
 async function authenticate(){if(!auth.email||auth.password.length<6)return setAuthMessage('กรุณากรอกอีเมลและรหัสผ่านอย่างน้อย 6 ตัวอักษร');setAuthMessage('กำลังดำเนินการ...');try{const endpoint=authMode==='login'?'token?grant_type=password':'signup';const r=await fetch(`${SUPABASE_URL}/auth/v1/${endpoint}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(auth)});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.message||'Authentication failed');if(data.access_token){localStorage.setItem(SESSION_KEY,JSON.stringify(data));setSession(data)}else setAuthMessage('สมัครเรียบร้อย กรุณาตรวจสอบอีเมลเพื่อยืนยันบัญชี')}catch(e){setAuthMessage(e.message)}}
 function logout(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem('taps-esg-session');setSession(null);setRecords([])}
 async function loadRecords(){setLoading(true);try{const r=await fetch(`${TABLE_URL}?select=*&order=record_date.desc,id.desc`,{headers:headers()});if(!r.ok)throw new Error(await r.text());setRecords(await r.json())}catch(e){alert(`โหลดข้อมูลไม่สำเร็จ: ${e.message}`)}finally{setLoading(false)}}
 function chooseSource(source){const f=factors[source];setForm(x=>({...x,source,scope:f.scope,unit:f.unit,emission_factor:f.factor}))}
 function resetForm(){setEditId(null);setForm({record_date:today,record_month:monthNow,factory:factories[0],company:companies[0],scope:2,source:'Electricity',activity_data:'',unit:'kWh',emission_factor:.4999,remark:''})}
 async function saveRecord(e){e.preventDefault();if(!form.activity_data||!form.emission_factor)return alert('กรุณากรอก Activity Data และ Emission Factor');const payload={...form,scope:Number(form.scope),activity_data:Number(form.activity_data),emission_factor:Number(form.emission_factor),remark:form.remark||null};setLoading(true);try{const r=await fetch(editId?`${TABLE_URL}?id=eq.${editId}`:TABLE_URL,{method:editId?'PATCH':'POST',headers:headers({Prefer:'return=representation'}),body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());resetForm();await loadRecords();setPage('records')}catch(e){alert(`บันทึกไม่สำเร็จ: ${e.message}`)}finally{setLoading(false)}}
 function editRecord(r){setEditId(r.id);setForm({record_date:r.record_date,record_month:r.record_month,factory:r.factory,company:r.company,scope:r.scope,source:r.source,activity_data:r.activity_data,unit:r.unit,emission_factor:r.emission_factor,remark:r.remark||''});setPage('entry');setMenuOpen(false)}
 async function deleteRecord(id){if(!confirm('ยืนยันลบรายการนี้?'))return;const r=await fetch(`${TABLE_URL}?id=eq.${id}`,{method:'DELETE',headers:headers()});if(!r.ok)return alert(await r.text());await loadRecords()}
 const filtered=useMemo(()=>records.filter(r=>{const k=`${r.source} ${r.remark||''}`.toLowerCase();return(!filter.search||k.includes(filter.search.toLowerCase()))&&(!filter.month||r.record_month===filter.month)&&(!filter.factory||r.factory===filter.factory)&&(!filter.scope||String(r.scope)===filter.scope)}),[records,filter]);
 const summary=useMemo(()=>{const scopes={1:0,2:0,3:0},months={},factoryMap={};records.forEach(r=>{const v=Number(r.tco2e||0);scopes[r.scope]+=v;months[r.record_month]=(months[r.record_month]||0)+v;factoryMap[r.factory]=(factoryMap[r.factory]||0)+v});return{scopes,total:scopes[1]+scopes[2]+scopes[3],months,factoryMap}},[records]);
 function exportCsv(){if(!filtered.length)return alert('ไม่มีข้อมูลสำหรับ Export');const rows=[['Date','Month','Factory','Company','Scope','Source','Activity','Unit','EF','tCO2e','Remark'],...filtered.map(r=>[r.record_date,r.record_month,r.factory,r.company,r.scope,r.source,r.activity_data,r.unit,r.emission_factor,r.tco2e,r.remark||''])];const csv='\ufeff'+rows.map(row=>row.map(cell=>`"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='APS_GHG_Data.csv';a.click();URL.revokeObjectURL(a.href)}
 const go=p=>{setPage(p);setMenuOpen(false)};
 if(!session)return <main className="loginPage"><section className="loginVisual"><ApsLogo/><p className="eyebrow light">APS ESG PLATFORM</p><h1>Environmental data.<br/>Clear decisions.</h1><p>ระบบบริหารข้อมูล GHG สำหรับ Amagasaki Pipe (Thailand)</p></section><section className="loginCard"><ApsLogo compact/><p className="eyebrow">SECURE CLOUD ACCESS</p><h2>{authMode==='login'?'ยินดีต้อนรับกลับ':'สร้างบัญชีผู้ใช้'}</h2><p className="loginIntro">เข้าสู่ระบบเพื่อจัดการข้อมูลและ Dashboard ขององค์กร</p><label>Email<input type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/></label><label>Password<input type="password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/></label><button className="primaryButton full" onClick={authenticate}>{authMode==='login'?'เข้าสู่ระบบ':'สมัครผู้ใช้'}</button><button className="textButton" onClick={()=>{setAuthMode(authMode==='login'?'signup':'login');setAuthMessage('')}}>{authMode==='login'?'ยังไม่มีบัญชี? สมัครผู้ใช้':'มีบัญชีแล้ว? เข้าสู่ระบบ'}</button><p className="statusMessage">{authMessage}</p></section></main>;
 const chart=Object.entries(summary.months).sort((a,b)=>a[0].localeCompare(b[0])).slice(-12),max=Math.max(...chart.map(([,v])=>v),1);
 const title=page==='dashboard'?'Executive Dashboard':page==='entry'?(editId?'Edit Activity':'New Activity'):page==='records'?'GHG Records':page==='factors'?'Emission Factor Library':'Report Center';
 return <div className="appShell"><aside className={`sidebar ${menuOpen?'open':''}`}><div className="brandBlock"><ApsLogo compact/><div><strong>APS ESG</strong><span>Enterprise · v0.7</span></div><button className="closeMenu" onClick={()=>setMenuOpen(false)}>×</button></div><nav>{navItems.map(([key,icon,label])=><button key={key} className={page===key?'active':''} onClick={()=>go(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebarFooter"><div className="userBadge"><b>{(session.user?.email||'U')[0].toUpperCase()}</b><span>{session.user?.email}</span></div><button onClick={logout}>ออกจากระบบ</button></div></aside>{menuOpen&&<button className="menuBackdrop" onClick={()=>setMenuOpen(false)}/>}<main className="workspace"><header className="topbar"><button className="menuButton" onClick={()=>setMenuOpen(true)}>☰</button><div className="titleBlock"><p className="eyebrow">AMAGASAKI PIPE (THAILAND)</p><h1>{title}</h1><p className="subtitle">Environmental performance and greenhouse gas management</p></div><div className="topActions"><span className="cloudStatus">● Cloud Connected</span><button className="iconButton" onClick={loadRecords}>↻</button></div></header>
 {page==='dashboard'&&<><section className="heroCard"><div><p className="eyebrow light">OVERVIEW</p><h2>Carbon performance at a glance</h2><p>ข้อมูลล่าสุดจาก Supabase Cloud พร้อมสำหรับการวิเคราะห์และรายงาน</p></div><button onClick={()=>go('entry')}>+ เพิ่มข้อมูล GHG</button></section><section className="kpiGrid">{[['Total Emission',summary.total,'All scopes'],['Scope 1',summary.scopes[1],'Direct'],['Scope 2',summary.scopes[2],'Electricity'],['Scope 3',summary.scopes[3],'Indirect']].map(([l,v,n])=><article className="kpiCard" key={l}><div><span>{l}</span><small>{n}</small></div><strong>{fmt(v)}</strong><em>tCO₂e</em></article>)}</section><section className="contentGrid"><article className="panel chartPanel"><div className="panelHeading"><div><p className="eyebrow">MONTHLY TREND</p><h2>Emission performance</h2></div><span className="recordPill">{records.length} records</span></div><div className="barChart">{chart.length?chart.map(([m,v])=><div className="barColumn" key={m}><div className="barValue">{fmt(v,1)}</div><div className="bar" style={{height:`${Math.max(v/max*190,5)}px`}}/><span>{m.slice(5)}</span></div>):<p className="emptyState">ยังไม่มีข้อมูลสำหรับแสดงกราฟ</p>}</div></article><article className="panel"><p className="eyebrow">TOP FACTORY</p><h2>Emission ranking</h2>{Object.entries(summary.factoryMap).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,v],i)=><div className="ranking" key={n}><b>{i+1}</b><span>{n}</span><strong>{fmt(v)}</strong></div>)}{!Object.keys(summary.factoryMap).length&&<p className="emptyState">ยังไม่มีข้อมูล</p>}</article></section></>}
 {page==='entry'&&<section className="panel formPanel"><div className="panelHeading"><div><p className="eyebrow">ACTIVITY DATA</p><h2>{editId?'แก้ไขข้อมูลกิจกรรม':'บันทึกข้อมูลกิจกรรมใหม่'}</h2></div><span className="recordPill">Auto calculation</span></div><form onSubmit={saveRecord}><div className="formGrid"><label>วันที่<input type="date" value={form.record_date} onChange={e=>setForm({...form,record_date:e.target.value,record_month:e.target.value.slice(0,7)})}/></label><label>เดือน<input type="month" value={form.record_month} onChange={e=>setForm({...form,record_month:e.target.value})}/></label><label>Factory<select value={form.factory} onChange={e=>setForm({...form,factory:e.target.value})}>{factories.map(x=><option key={x}>{x}</option>)}</select></label><label>Company<select value={form.company} onChange={e=>setForm({...form,company:e.target.value})}>{companies.map(x=><option key={x}>{x}</option>)}</select></label><label>Emission Source<select value={form.source} onChange={e=>chooseSource(e.target.value)}>{Object.keys(factors).map(x=><option key={x}>{x}</option>)}</select></label><label>Scope<select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})}><option value="1">Scope 1</option><option value="2">Scope 2</option><option value="3">Scope 3</option></select></label><label>Activity Data<input type="number" min="0" step="any" value={form.activity_data} onChange={e=>setForm({...form,activity_data:e.target.value})}/></label><label>Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Emission Factor<input type="number" min="0" step="any" value={form.emission_factor} onChange={e=>setForm({...form,emission_factor:e.target.value})}/></label><label className="spanThree">Remark<textarea value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})}/></label></div><div className="formActions"><button type="button" className="outlineButton" onClick={resetForm}>ล้างฟอร์ม</button><button className="primaryButton" disabled={loading}>{loading?'กำลังบันทึก...':editId?'บันทึกการแก้ไข':'บันทึกข้อมูล'}</button></div></form></section>}
 {page==='records'&&<section className="panel"><div className="panelHeading"><div><p className="eyebrow">DATABASE</p><h2>GHG Records</h2></div><button className="primaryButton" onClick={exportCsv}>Export CSV</button></div><div className="filterBar"><input placeholder="ค้นหา Source / Remark" value={filter.search} onChange={e=>setFilter({...filter,search:e.target.value})}/><input type="month" value={filter.month} onChange={e=>setFilter({...filter,month:e.target.value})}/><select value={filter.factory} onChange={e=>setFilter({...filter,factory:e.target.value})}><option value="">ทุก Factory</option>{factories.map(x=><option key={x}>{x}</option>)}</select><select value={filter.scope} onChange={e=>setFilter({...filter,scope:e.target.value})}><option value="">ทุก Scope</option><option value="1">Scope 1</option><option value="2">Scope 2</option><option value="3">Scope 3</option></select></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Factory</th><th>Scope</th><th>Source</th><th>Activity</th><th>Unit</th><th>tCO₂e</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.record_date}</td><td>{r.factory}</td><td><span className={`scopeTag s${r.scope}`}>Scope {r.scope}</span></td><td>{r.source}</td><td>{fmt(r.activity_data,2)}</td><td>{r.unit}</td><td><strong>{fmt(r.tco2e)}</strong></td><td><button className="tableButton" onClick={()=>editRecord(r)}>Edit</button><button className="tableButton dangerText" onClick={()=>deleteRecord(r.id)}>Delete</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="emptyState">ไม่พบข้อมูล</p>}</div></section>}
 {page==='factors'&&<section className="panel"><p className="eyebrow">REFERENCE DATA</p><h2>Emission Factor Library</h2><div className="tableWrap"><table><thead><tr><th>Source</th><th>Scope</th><th>Unit</th><th>Emission Factor</th></tr></thead><tbody>{Object.entries(factors).map(([n,f])=><tr key={n}><td><strong>{n}</strong></td><td>Scope {f.scope}</td><td>{f.unit}</td><td>{f.factor}</td></tr>)}</tbody></table></div><p className="helperText">ค่าปัจจุบันเป็นข้อมูลตัวอย่าง กรุณาตรวจสอบกับแหล่งอ้างอิงที่บริษัทอนุมัติก่อนใช้งานจริง</p></section>}
 {page==='reports'&&<section className="panel reportEmpty"><div className="reportIcon">▤</div><p className="eyebrow">REPORT CENTER</p><h2>Corporate reporting workspace</h2><p>Export CSV ใช้งานได้แล้ว ส่วน Excel, PDF และ Carbon Footprint Report จะเพิ่มใน Sprint ถัดไป</p><button className="primaryButton" onClick={exportCsv}>Export current data</button></section>}</main><nav className="mobileNav">{navItems.slice(0,4).map(([k,i,l])=><button key={k} className={page===k?'active':''} onClick={()=>go(k)}><span>{i}</span><small>{l.replace('GHG ','')}</small></button>)}</nav></div>
}
